services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/python:3.12
    container_name: python
    platform: linux/amd64
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on: 
      - db

  db:
    image: icr.io/db2_community/db2:latest
    hostname: db
    container_name: db
    privileged: true
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "50000:50000"
    volumes:
      - db2-data:/database
    environment:
      LICENSE: accept
      DB2INSTANCE: db2inst1
      DB2INST1_PASSWORD: password
      DBNAME: testdb
      DB2COMM: TCPIP
#      BLU: false
#      ENABLE_ORACLE_COMPATIBILITY: false
#      UPDATEAVAIL: NO
      TO_CREATE_SAMPLEDB: true
#      REPODB: false
#      IS_OSXFS: false
#      PERSISTENT_HOME: true
#      HADR_ENABLED: false

volumes:
  db2-data: